### ISSUE TITLE
Gem installation failing

### ISSUE THREAD

**Issue by dazinator** [romanbsd/fast-stemmer#10]
Having issues on Windows installing this gem.

As recorded here: https://talk.jekyllrb.com/t/jekyll-error-failed-to-build-gem-native-extension/430/2

This is the problem:

``` csharp
C:\Users\darrell.tunnell\Source\Repos\dazinator.github.io>bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using RedCloth 4.2.9
Using blankslate 2.1.2.4
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using chunky_png 1.3.4

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

C:/Ruby193/bin/ruby.exe -r ./siteconf20150528-1132-13jp7fp.rb extconf.rb
creating Makefile

make clean
Makefile:165: *** target pattern contains no `%'. Stop.

make
Makefile:165: *** target pattern contains no `%'. Stop.

make failed, exit code 2

Gem files will remain installed in C:/Ruby193/lib/ruby/gems/1.9.1/gems/fast-stem
mer-1.0.2 for inspection.
Results logged to C:/Ruby193/lib/ruby/gems/1.9.1/extensions/x86-mingw32/1.9.1/fa
st-stemmer-1.0.2/gem_make.out
An error occurred while installing fast-stemmer (1.0.2), and Bundler cannot
continue.
Make sure that gem install fast-stemmer -v '1.0.2' succeeds before bundling.
```

Any ideas?

**Comment by romanbsd** [comment]
I don't have Windows. But if you know how to fix it, I'll be happy to merge the fix.

**Comment by dazinator** [comment]
Sorry, i'm way out of my area of expertise here. I'm a .NET developer by trade. Started an OctoPress blog which is Jekyll based, and installing Jekyll lead me here as I assume this is a dependency of Jekyll? If I could help I would gladly :(

**Comment by dazinator** [comment]
But.. I just found this which looks to be the same issue - maybe it will make more sense to you though: https://github.com/rubygems/rubygems/issues/977

**Comment by dazinator** [comment]
Ok - the solution to this on windows seems to be to downgrade ruby gems version.

`gem update --system 2.3.0`

I'll try that. Will close this issue as it appears to be nothing to do with your package itself but a ruby gems issue.

**Comment by esteinborn** [comment]
I can verify that downgrading ruby gem version to 2.3.0 fixes this error message in Windows environments. Thanks for the answer.
