### ISSUE TITLE
Windows 10 build fails

### ISSUE THREAD

**Issue by ErikSchierboom** [romanbsd/fast-stemmer#11]
I am trying to install `fast-stemmer` on my Windows 10 machine, but it fails. I have tried to search for this error but didn't find a similar one. The solution that worked for others to set the gem version to 2.3.0 also didn't work. This is the error:

<pre>
Installing fast-stemmer 1.0.2 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/tools/Ruby21-x64/bin/ruby.exe extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating stemmer-x64-mingw32.def
      0 [main] sh 1404 fork_copy: linked dll data/bss pass 0 failed, 0x4E8000..0
x4E8AD8, done 0, windows pid 4212, Win32 error 487
/bin/sh: fork: Resource temporarily unavailable
make: *** [stemmer-x64-mingw32.def] Error 128

make failed, exit code 2

Gem files will remain installed in C:/tools/Ruby21-x64/lib/ruby/gems/2.1.0/gems/
fast-stemmer-1.0.2 for inspection.
Results logged to C:/tools/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32
/2.1.0/fast-stemmer-1.0.2/gem_make.out
An error occurred while installing fast-stemmer (1.0.2), and Bundler cannot
continue.
Make sure that `gem install fast-stemmer -v '1.0.2'` succeeds before bundling.
</pre>

**Comment by romanbsd** [comment]
Unfortunately I don't have a windows machine. Hopefully someone will find a solution for this.

**Comment by dgoerdes** [comment]
run the command in a console that is running with admin permissions!

**Comment by ErikSchierboom** [comment]
Thanks. That works.
