### ISSUE TITLE
Early English Stemmer

### ISSUE THREAD

**Issue by ylluminate** [romanbsd/fast-stemmer#3]
Could you please integrate early English stemming capacity into fast-stemmer as per http://snowball.tartarus.org/texts/earlyenglish.html?

It would be amazing if we could simply call .stem_early or something of that nature to execute early English stemming on words.

**Comment by ylluminate** [comment]
FYI, I did attempt to crudely modify your code (I'm not convinced it's the only change that's needed) to allow for the specified additions, however when I try to build the gem with a `gem build fast-stemmer.gemspec` I get back:

```
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["ext/Makefile"] are not files
```

**Comment by romanbsd** [comment]
I don't think that adding it w/o some refactoring of the original Porter code is possible. And I wouldn't want to include early English by default. Having said that, I'm willing to include such change, if it's backward compatible.
For building a gem, please use "rake build"
