### ISSUE TITLE
Compile issue with latest ruby build 1.9.3-p392

### ISSUE THREAD

**Issue by debo** [romanbsd/fast-stemmer#5]
I'm trying to install Jekyll which depends on fast-stemmer. Sadly the installation fails with the following error:

$ gem install jekyll
Successfully installed liquid-2.5.0
Fetching: fast-stemmer-1.0.2.gem (100%)
Building native extensions.  This could take a while...
        ERROR:  Error installing jekyll:
    ERROR: Failed to build gem native extension.

/Users/debo/.rbenv/versions/1.9.3-p392/bin/ruby extconf.rb
/Users/debo/.rbenv/versions/1.9.3-p392/bin/ruby: invalid option -g  (-h will show valid options) (RuntimeError)

Gem files will remain installed in /Users/debo/.rbenv/versions/1.9.3-p392/gemsets/magetest global/gems/fast-stemmer-1.0.2 for inspection.
Results logged to /Users/debo/.rbenv/versions/1.9.3-p392/gemsets/magetest global/gems/fast-stemmer-1.0.2/ext/gem_make.out

However everything for previous versions such as ruby 1.9.3-p194

Any ideas? Any help will be very much appreciated.

Thanks,
Debo

**Comment by AlexanderEkdahl** [comment]
The output of `/Users/debo/.rbenv/versions/1.9.3-p392/gemsets/magetest global/gems/fast-stemmer-1.0.2/ext/gem_make.out` might help!

**Comment by debo** [comment]
I wish, the output of that file is just:

/Users/debo/.rbenv/versions/1.9.3-p392/bin/ruby extconf.rb
/Users/debo/.rbenv/versions/1.9.3-p392/bin/ruby: invalid option -g (-h will show valid options) (RuntimeError)

For the time being I solved downgrading my local ruby to 1.9.3-p194. It did the trick for the time being.

**Comment by romanbsd** [comment]
It installs just fine here on 1.9.3-p392. Check that you don't have some weird wrapper around your ruby.
I'm using rvm, btw.

**Comment by debo** [comment]
@romanbsd I'm using rbenv here...

**Comment by debo** [comment]
Ok I don't know exactly where the problem was but uninstalling and rebuilding ruby 1.9.3-p392 and following reinstalling the needed gems did the trick. Probably something went wrong within my previous build.
