### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jonasrla** [romanbsd/fast-stemmer#6]
I'm using the 2.1.10 version gem and getting this when I try to install your application:

MacBook-Pro-de-Jonas-Rocha-Lima-Amaro-2:ext jonasrla$ sudo gem install fast-stemmer
Building native extensions.  This could take a while...
ERROR:  Error installing fast-stemmer:
    ERROR: Failed to build gem native extension.

Gem files will remain installed in /opt/local/lib/ruby2.0/gems/2.0.0/gems/fast-stemmer-1.0.2 for inspection.
Results logged to /opt/local/lib/ruby2.0/gems/2.0.0/gems/fast-stemmer-1.0.2/ext/gem_make.out

**Comment by romanbsd** [comment]
And what does the  /opt/local/lib/ruby2.0/gems/2.0.0/gems/fast-stemmer-1.0.2/ext/gem_make.out say?

**Comment by jonasrla** [comment]
I accessed the file with vim and found a readonly empty file.

**Comment by romanbsd** [comment]
Looks like a problem with permissions. Or, perhaps, you don't have the compiler toolchain installed...

**Comment by jonasrla** [comment]
Solved. One of the tries said that the gcc4-2 couldn't be found so I linked the directory it was looking to the gcc directory and it installed successfully

**Comment by allanhortle** [comment]
Just to note. I'm having this issue also. I'll try linking gcc. But this certainly isn't isolated. I've seen a lot of Jekyll users with this issue.
