### ISSUE TITLE
clang: error: unknown argument: '-multiply_definedsuppress' [-Wunused-command-line-argument-hard-error-in-future]

### ISSUE THREAD

**Issue by parkr** [romanbsd/fast-stemmer#9]
Compilation error on Mac OS X with Xcode 5.1 seems to be failing more than usual. Have you seen this? Full `gem_make.out` dumps in the issues below:

Ref: https://github.com/jekyll/jekyll/issues/2125 & related issues

**Comment by romanbsd** [comment]
No idea, actually. Works fine here.

**Comment by parkr** [comment]
Yeah it works fine for me, too. We've just seen about 8 or so people in the last week have this problem. Do you set a `unused-command-line-argument-hard-error-in-future` flag anywhere?

**Comment by thissophie** [comment]
``` bash
ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install fast-stemmer
```

Works around this issue for now.

**Comment by Blaisorblade** [comment]
> Do you set a unused-command-line-argument-hard-error-in-future flag anywhere?

That's a default — EDIT: for newer clang.

https://langui.sh/2014/03/10/wunused-command-line-argument-hard-error-in-future-is-a-harsh-mistress/

**Comment by Blaisorblade** [comment]
A pitfall in your workaround: installation requires sudo for me, on OS X (see 2. below), and the option must be specified "inside" sudo (see 1.), not outside (see 3.), because sudo removes environment variables by default for security reasons:
1. Correct:
   
   > sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install fast-stemmer
2. Installation without sudo:
   
   > ERROR:  While executing gem ... (Gem::FilePermissionError)
   > You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
3. This fails with the same error:
   
   > ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future" sudo gem install fast-stemmer

**Comment by timothyekl** [comment]
@Blaisorblade: try preserving the environment by passing the `-E` option to `sudo`, e.g.:

```
ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future sudo -E gem install fast-stemmer
```

**Comment by Blaisorblade** [comment]
That works, as well as my solution 1.
But to clarify: my comment is for reference to other people finding this (if any), I already found a workaround. Thanks a lot anyway!

**Comment by kommi10** [comment]
"try preserving the environment by passing the -E option to sudo, e.g.:"

That worked for me, thanks @lithium3141!

**Comment by siegfang** [comment]
Now, you can just update to OS X 10.9.3 to fix this problem!
